# Generated by Django 3.0.8 on 2021-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_fresher',
            field=models.BooleanField(default=True),
        ),
    ]
