# Generated by Django 3.0.8 on 2021-03-24 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210322_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
