# Generated by Django 3.0.8 on 2021-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
