# Generated by Django 3.0.8 on 2021-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210324_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
